加了几道题？
uzkk/quiz pull request #29
Opened 2019-04-27 16:31 UTC by Kagurazaka-Chiaki

**半自动**加了二十一道题……（嗯……离全自动不远了……大概）

2019-04-27 17:03 UTC, shigma commented on lib/data/easy.yaml
> +  - 阿空是地狱鸦＋八咫乌，衣玖是皇带鱼，朱鹭子是朱鹮，星是老虎.
这个加号好迷啊……就普通无空格的英文+好了

全角句号。

2019-04-27 17:03 UTC, shigma commented on lib/data/easy.yaml
> +  - 凭依华中指出依神紫苑拥有“使人消耗财产程度的能力”。（顺便一提：哭泣的孩子究竟做错了什么？）
《》

两处都应该为“依神女苑”，对不起是我的错。

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +- - 克劳恩皮丝零设是源于哪个神话？
**零设放到 E 分类。**

建议选项：
- 希腊神话
- 罗马神话
- 北欧神话
- 凯尔特神话

建议解析：
> 克劳恩皮丝的零设是希腊神话中冥界的宁芙（ニュンペー，Nymph）。作为魔法女神赫卡忒的同伴，夜晚降临时手持火炬，与其一同进行仪式或是招来鬼怪。

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +  - -苏我屠自古：神明后裔的亡灵（《东方神灵庙》，《东方求闻口授》）；
`- - 苏我屠自古`，这个是语法错误了，注意一下。

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +  - -苏我屠自古：神明后裔的亡灵（《东方神灵庙》，《东方求闻口授》）；
建议描述作品的括号内不再加入书名号，例如：`（东方神灵庙，东方求闻口授）`。下同。

（刚刚决定的规矩，以后都这么写好了。）

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +    - 克劳恩皮丝：地狱的妖精（《东方绀珠传》），狂气的地狱妖精（《东方三月精 ~ Visionary Fairies in Shrine》）。
东方三月精 V 可以直接写

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +    - 哆来咪在《东方绀珠传》立绘中可见一条长长的尾巴。
建议把非引文放在一起，引文放在一起。

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +      source: 《东方天空璋》Music Room，3 面 Boss 高丽野阿吽主题曲
建议：

```yaml
text: 虽然看不见但她（高丽野阿吽）也有尾巴的喔。
source: 《东方天空璋》Music Room
```

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +  - -米斯蒂娅·萝蕾拉在《东方永夜抄》中有符卡“毒符「毒蛾的鳞粉」”；
`- - 米斯蒂娅`，这大概是你的脚本出了点问题哈哈

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +- - 以下哪位角色没有尾巴？
建议 N 难度。

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +  - -蕾米莉亚·斯卡蕾特：红符「Scarlet Meister」；
同上。

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +- - 以下哪张符卡有符名（但是被漏掉了）？
这题好像已经有了啊……

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +- - 在东方星莲船EX中请问恨弓『源三位赖政之弓』共有几个阶段？
推荐表述：

> 符卡“恨弓『源三位赖政之弓』”共有几个阶段？

建议难度 N。

2019-04-27 17:03 UTC, shigma commented on lib/data/hard.yaml
> +- - 蕾米莉亚·斯卡蕾特在《东方非想天则》中，未在以下哪个场景出现？
推荐表述：

> 在《东方非想天则》中，蕾米莉亚·斯卡蕾特未在以下哪个场景出现？

2019-04-27 17:03 UTC, shigma commented on lib/data/lunatic.yaml
> +  - -八云紫仅正面能看到的蝴蝶结就有10个(还不算隙间上的那两个；
同上。

2019-04-27 17:03 UTC, shigma commented on lib/data/lunatic.yaml
> +  - -八云紫仅正面能看到的蝴蝶结就有10个(还不算隙间上的那两个；
推荐表述：

> 八云紫仅正面能看到的蝴蝶结就有 10 个（还不算隙间上的那两个）；

2019-04-27 17:03 UTC, shigma commented on lib/data/lunatic.yaml
> +    - 藤原妹红共八个；
如果一处用阿拉伯数字的话就统一使用阿拉伯数字，下同。

2019-04-27 17:03 UTC, shigma commented on lib/data/lunatic.yaml
> +  - c
这里出现了一些 trailing space（尾随空格），可能是脚本的问题，虽然看起来关系不大但还是删一下吧。

2019-04-27 17:03 UTC, shigma commented on lib/data/normal.yaml
> +  - 灵乌路空的种族是地狱鸦 with 八咫乌
。

2019-04-27 17:03 UTC, shigma commented on lib/data/normal.yaml
> +  - 灵乌路空的种族是地狱鸦 with 八咫乌
建议 E 难度

2019-04-27 17:03 UTC, shigma commented on lib/data/normal.yaml
> +  - 二婶子你又去打发胶了！/斜眼笑
/斜眼笑

2019-04-27 17:03 UTC, shigma commented on lib/data/normal.yaml
> +  - 二婶子你又去打发胶了！/斜眼笑
😏这个怎么样？觉得好的话就直接复制进去吧~

2019-04-27 17:03 UTC, shigma commented on lib/data/normal.yaml
> +  - -你能清楚的记得到今天为止吃过的面包的数量吗？
quote

2019-04-27 17:03 UTC, shigma commented on lib/data/pending.yaml
> +- - 滲色血界、月狂ノ獄中，蕾米莉亚·斯卡蕾特总共喊了几声“暗い”（好暗）？
《滲色血界、月狂ノ獄》

2019-04-27 17:03 UTC, Shigma commented on lib/data/normal.yaml
> +    - 你还不明白吗？你已经输给了命运...
……

2019-04-27 17:03 UTC, Shigma commented on lib/data/lunatic.yaml
> +  - 帽子上是天琴座，左上大熊座，右上仙后座，左下仙女座，右下人马座。
左上 -> 衣服左边。其他同理。

2019-04-27 17:03 UTC, Shigma commented on lib/data/lunatic.yaml
> +  - c
其实有每道题都出现了，你可以尝试通过正则替换的方式统一删除。

2019-04-27 17:06 UTC, Shigma commented
长直发那道题是不是漏掉了？

2019-04-27 17:06 UTC, Shigma commented
以下哪一张符卡的名字中不含平假名？
禁忌「四重存在」
秘法「九字切」
转世「一条归桥」
雨符「雨夜怪谈」
禁忌「フォーオブアカインド」；秘法「九字刺し」；転世「一条戻り橋」；雨符「雨夜の怪談」。
shigma，He

2019-04-27 17:07 UTC, Shigma commented
以下哪位人物不是长直发？
圣白莲
比那名居天子
斯塔·萨菲娅
蓬莱山辉夜
莲妈可是烫头穿紧身衣骑摩的的老尼姑呢~
Iku_Artyomov，Ec

2019-04-27 17:14 UTC, Kouchya commented on lib/data/normal.yaml
> +  - 灵乌路空的种族是地狱鸦 with 八咫乌
前面有一题写的是地狱鸦+八咫乌，这里写的 with，可以考虑统一？

2019-04-27 17:16 UTC, Shigma commented on lib/data/easy.yaml
> +  - 阿空是地狱鸦＋八咫乌，衣玖是皇带鱼，朱鹭子是朱鹮，星是老虎.
@Kouchya 说得对……设定文档里面好像是 with，那就别用加号了吧（

2019-04-27 17:16 UTC, Shigma commented on lib/data/hard.yaml
> +  - -蕾米莉亚·斯卡蕾特：红符「Scarlet Meister」；
如果下面两个角色写的是简称的话，建议直接使用蕾米莉亚；或者下面两个角色使用全称。

2019-04-27 17:32 UTC, Kagurazaka-Chiaki commented
"以下哪位人物不是长直发？" 这道题好像是本来就有？

2019-04-27 18:54 UTC, Shigma commented on lib/data/hard.yaml
> +- - 在东方星莲船EX中请问符卡“恨弓『源三位赖政之弓』”共有几个阶段？
“在东方星莲船EX中请问”直接删掉为好

2019-04-27 18:54 UTC, Shigma commented on lib/data/normal.yaml
> +  - -蕾米莉亚·斯卡蕾特：红符「Scarlet Meister」；
还是缺空格。

2019-04-27 18:54 UTC, Shigma commented on lib/data/easy.yaml
>  - - 以下哪位角色的原型或种族不是现实中存在的动物？
@Kouchya 这里跟上面一道题有重复之嫌，你的意见？

2019-04-27 18:57 UTC, Kouchya commented on lib/data/easy.yaml
>  - - 以下哪位角色的原型或种族不是现实中存在的动物？
考虑将这题移入 N 难度？感觉 19 的羽衣这设定看着挺神仙 233
（这是出于尽可能保住题目本身的考虑，如果调整难度显得牵强，两个删哪个我觉得都行 233

2019-04-27 19:00 UTC, Shigma commented on lib/data/normal.yaml
> +
多一个空行

2019-04-27 19:07 UTC, Shigma commented on lib/data/easy.yaml
>  - - 以下哪位角色的原型或种族不是现实中存在的动物？
或者我们把这个选项换掉吧？

2019-04-27 19:12 UTC, Shigma commented on lib/data/easy.yaml
>  - - 以下哪位角色的原型或种族不是现实中存在的动物？
@Kagurazaka-Chiaki 我觉得正确选项可以改成幽谷响子（山彦）

2019-04-27 19:34 UTC, Kouchya requested changes
@Kagurazaka-Chiaki 辛苦了，还剩一点需要改动的地方，有劳你了

2019-04-27 19:34 UTC, Kouchya commented on lib/data/hard.yaml
> +  - 当你决定进入 p4 拖全避的时候，耗 30 秒即可进入 p5。
解析或许这么写稍显正式些？
> 进入 p4 持续 30 秒后将进入 p5。

2019-04-27 19:34 UTC, Kouchya commented on lib/data/hard.yaml
> +  - 克劳恩皮丝的零设是希腊神话中冥界的宁芙（ニュンペー，Nymph）。作为魔法女神赫卡忒的同伴，夜晚降临时手持火炬，与其一同进行仪式或是招来鬼怪。
抱歉虽然有点琐碎，但一般讨论希腊神话中“冥界的宁芙”时，好像都以“拉姆帕德斯”称呼而非“宁芙”来着 233
（另外，这个似乎不是东方原作或访谈的引文，希腊神的名字冒出来日语是不是显得有点违和……？个人感觉也许不用加括号及外语？

2019-04-27 19:34 UTC, Kouchya commented on lib/data/lunatic.yaml
> +  - 9961
选项里曲名按规范的话，除了纯英文曲名以外，都是要写成“原名（翻译）”这样的格式，举例如下：
- Maniacal Princess
- 夜の鳩山を飛ぶ（飞翔于夜晚的鸠山）

（解析里按规范就像现在这样，不用改

2019-04-27 19:34 UTC, Kouchya commented on lib/data/normal.yaml
> +  - shigma
（选项中角色名按规范是要写全名的说

2019-04-27 19:34 UTC, Kouchya commented on lib/data/pending.yaml
> +  - 黑白色の魔理沙
诶，有两个选项都是11？
（第四个选项的 11 改成 8 或改成 12 叭

2019-04-27 19:34 UTC, Kouchya commented on lib/data/lunatic.yaml
> +  - 《飞翔于夜晚的鸠山》是乐句整体移调，《少女神性》《Demystify Feast》均为动机移调；《Maniacal Princess》在开头有一个移调但是主旋律有微妙的不同，在主题有一个“上升”但并没有移调。
@Shigma 这里你觉得需要换行解析吗？

2019-04-27 19:34 UTC, Kouchya commented on lib/data/lunatic.yaml
> +  - Rachael
这题截至发这条 comment 时尚有疑问未解决，在群里讨论解决之前留着这个 comment 防止合并

2019-04-27 19:36 UTC, Kouchya commented on lib/data/pending.yaml
> +  - 黑白色の魔理沙
啊，没看到是 pending 233
不过有余力的话还是麻烦改一下叭~

2019-04-28 02:45 UTC, Shigma commented on lib/data/normal.yaml
> +  - 《东方神灵庙》的立绘中，二岩猯藏的左侧是酒壶，右侧是账簿，头顶有一片树叶；烟斗则出现在《东方深秘录》的立绘中。
《东方心绮楼》《东方深秘录》《东方凭依华》

2019-04-28 07:51 UTC, Kouchya requested changes

2019-04-28 07:51 UTC, Kouchya commented on lib/data/lunatic.yaml
> +  - 9961
解析里曲名按规范是不写完整的……写成诸如《Maniacal Princess》《少女神性》这样就行

2019-04-28 09:02 UTC, Shigma commented on lib/data/lunatic.yaml
> +    - 《少女神性 》《Demystify Feast》均为动机移调；
多一个空格

2019-04-28 09:02 UTC, Shigma commented on lib/data/normal.yaml
> -  - 《东方神灵庙》的立绘中，二岩猯藏的左侧是酒壶，右侧是账簿，头顶有一片树叶；烟斗则出现在《东方深秘录》的立绘中。
不是这个意思。

> 《东方神灵庙》的立绘中，二岩猯藏的左侧是酒壶，右侧是账簿，头顶有一片树叶；烟斗则出现在《东方心绮楼》《东方深秘录》《东方凭依华》的立绘中。

2019-04-28 10:01 UTC, Shigma commented on lib/data/lunatic.yaml
> +  - Rachael
删掉吧

2019-04-28 10:04 UTC, shigma approved these changes
这次真的辛苦了。

顺便半自动很赞。👍

2019-04-28 10:05 UTC, merged