加了几道题？
uzkk/quiz pull request #33
Opened 2019-05-03 09:35 UTC by Kagurazaka-Chiaki

加了十道题……

2019-05-03 11:28 UTC, Shigma commented on lib/data/hard.yaml
> +  - type: quote
不是直接引文，因而不建议这么写。

> 在《东方儚月抄》漫画的第十五话中，绵月依姬无意尝到了魔理沙的弹幕，并表示“好甜”。

2019-05-03 11:28 UTC, Shigma commented on lib/data/lunatic.yaml
> +- - 以下哪位角色在其初登场游戏立绘中穿着鞋子？
初登场作品

2019-05-03 11:28 UTC, Shigma commented on lib/data/lunatic.yaml
> +  - 鬼人正邪在《东方辉针城》立绘中穿着拖鞋（就外表而言，可能是有着紫色宽鼻緒的舟形下駄（www.getaya.org/fgeta/），当然也可能只是普通的拖鞋）。（太难了，必须L）
这个鞋子叫舟形下駄的确很难，但是这道题本身应该是 E 难度的。@kouchya

2019-05-03 11:28 UTC, Shigma commented on lib/data/lunatic.yaml
> +- - 以下哪位角色在《东方求闻史纪》中的立绘看不到正脸？
特征教上一题更为明显。建议 H。

2019-05-03 11:28 UTC, Shigma commented on lib/data/lunatic.yaml
> +- - 以下哪位角色在其初登场游戏中的符卡名均没有短横杠“-”？
记得其他某道题好像用的是括号而不是引号，@kouchya 你再去确定一下。

2019-05-03 11:28 UTC, Shigma commented on lib/data/normal.yaml
> +- - 古明地觉是《东方地灵殿》的几面boss？
Boss，空格

2019-05-03 11:28 UTC, Shigma commented on lib/data/normal.yaml
> +  - 地灵殿殿主肯定是6面boss啊。错乱……
> 觉可能是最没有威严的统治者了（

2019-05-03 11:28 UTC, Shigma commented on lib/data/normal.yaml
> +- - 东风谷早苗的种族是？
我觉得有一定争议。建议 pending。

@Kouchya

2019-05-03 11:28 UTC, Shigma commented on lib/data/normal.yaml
> +- - 以下哪张符卡中，敌机的enemy标志不会消失？
啊……这题直接删掉吧

2019-05-03 12:04 UTC, Kouchya requested changes

2019-05-03 12:04 UTC, Kouchya commented on lib/data/hard.yaml
> +    text: （绵月依姬无意尝到了魔理沙的弹幕，并表示）“好甜”。
引文不需要引号叭？

2019-05-03 12:04 UTC, Kouchya commented on lib/data/hard.yaml
> +  - Racbael
是 Rachael，这应该是孤梦在群里写错了你直接复制了233

2019-05-03 12:04 UTC, Kouchya commented on lib/data/lunatic.yaml
> +  - 鬼人正邪在《东方辉针城》立绘中穿着拖鞋（就外表而言，可能是有着紫色宽鼻緒的舟形下駄（www.getaya.org/fgeta/），当然也可能只是普通的拖鞋）。（太难了，必须L）
噗……被扔 L 是什么情况 233，建议 E

2019-05-03 12:04 UTC, Kouchya commented on lib/data/lunatic.yaml
> +- - 以下哪位角色在《东方求闻口授》中的立绘是俯角的？
此题建议 H，题干改为“以下哪位角色在《东方求闻口授》中的立绘是仰视的？”，解析改为“布都、雏和小伞在《东方求闻口授》中的立绘均平视前方，而帕露西是略微抬头仰视的。”

2019-05-03 12:04 UTC, Kouchya commented on lib/data/lunatic.yaml
> +- - 以下哪位角色在《东方求闻史纪》中的立绘看不到正脸？
（其实我觉得 N 就差不多（小声）

2019-05-03 12:04 UTC, Kouchya commented on lib/data/lunatic.yaml
> +- - 以下哪位角色在其初登场游戏中的符卡名均没有短横杠“-”？
是的，音乐日文名结尾句点那题用的括号。所以此题题干最后改为：短横杠（-）
另外建议 N 难度，与卡名中含阿拉伯数字那题相同。

2019-05-03 12:04 UTC, Kouchya commented on lib/data/normal.yaml
> +  - Racbael
Rachael

2019-05-03 12:04 UTC, Kouchya commented on lib/data/normal.yaml
> +  - 地灵殿殿主肯定是6面boss啊。错乱……
另外麻烦加个空格~

2019-05-03 12:04 UTC, Kouchya commented on lib/data/normal.yaml
> +- - 东风谷早苗的种族是？
各作设定文档里种族一栏清一色写着人类，没有写现人神。我找到的“现人神”好像仅出现在称号和文档介绍里，而且没有声明过这是早苗的种族。
不过我不擅长斟酌一设文档各处出现的语言争议，还是你一锤定音叭 @Shigma

2019-05-03 12:04 UTC, Kouchya commented on lib/data/normal.yaml
> +  - Racbael
Rachael

2019-05-03 12:08 UTC, Kouchya requested changes
又找到几个署名 typo

2019-05-03 12:08 UTC, Kouchya commented on lib/data/normal.yaml
> +  - Racbael
Rachael

2019-05-03 12:08 UTC, Kouchya commented on lib/data/normal.yaml
> +  - Racbael
Rachael

2019-05-03 12:11 UTC, Shigma commented on lib/data/normal.yaml
> +  - 地灵殿殿主肯定是6面boss啊。错乱……
直接改成我那句吧，空格不用了（

2019-05-03 12:11 UTC, Shigma commented on lib/data/normal.yaml
> +- - 东风谷早苗的种族是？
建议先 pending，之后我会多问几个人。

2019-05-03 12:11 UTC, Shigma commented on lib/data/lunatic.yaml
> +- - 以下哪位角色在其初登场游戏中的符卡名均没有短横杠“-”？
同意。

2019-05-03 12:11 UTC, Shigma commented on lib/data/lunatic.yaml
> +- - 以下哪位角色在《东方求闻史纪》中的立绘看不到正脸？
那就 N。

2019-05-04 16:03 UTC, shigma reviewed
就这一点了……

2019-05-04 16:03 UTC, Shigma commented on lib/data/normal.yaml
> +- - 古明地觉是《东方地灵殿》的几面 boss？
Boss

2019-05-05 09:32 UTC, shigma approved these changes
辛苦了

2019-05-05 09:32 UTC, merged