加了几道题？
uzkk/quiz pull request #34
Opened 2019-05-06 12:19 UTC by Kagurazaka-Chiaki

加了三十九道题……冷酷无情的出题机器233……

2019-05-06 12:47 UTC, shigma reviewed
要改的地方比较多，分几波 review 吧。

有一些地方总体提一下：

1. “迷失竹林”统一改成“迷途竹林”，遵循 THBWiki 的说法。
2. 求闻史纪中的引用，一律补全篇名。

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +  - - (你们这个药店肯定越办越好啊(划掉
> 稀神探女：你们这个药店肯定越办越好啊（划掉

同时建议放到引文的下面。

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +- - 《东方星莲船》里提到的关于命莲飞钵移粮出自《信贵山缘起》的哪一卷？
零设，E

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +  - 零设中，《东方星莲船》里提到的关于命莲飞钵移粮的传说出自山崎长者卷，（故事大意）信浓国法师“命莲”有通神之力，在信贵山中修行。在山上建造毘沙门天祭祀堂。命莲下山传道之时，用法力控制一个会飞的托钵，向一位富庶人家的长者化缘。有一天，当托钵像往常一样飞来化缘时，富人说：“好有意思的托钵啊！”于是偷偷将托钵放在了粮仓的角落里，随后锁上了粮仓的大门。谁知整个粮仓震动了起来，随即漂浮在了空中。接着
> 零设中，《东方星莲船》里提到的关于命莲飞钵移粮的传说出自山崎长者卷。故事大意：

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +- - 《东方星莲船》里提到的关于千里治病出自《信贵山缘起》的哪一卷？
零设，E

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +  - 零设中，《东方星莲船》里提到的关于命莲飞钵移粮的传说出自延喜加持卷。（故事大意）法师传道途中得知醍醐天皇病重，便暗自为他祈福。有人向天皇谏言：“听闻有一命莲法师通晓法术，会用法力让托钵飞起。其隐居在山中，不如派人召见，说不定能治愈天皇您的病。”使者找到了命莲，向他表明了来由。于是命莲便亲自做法，为天皇祈福。使者又问：“如果天皇的病好了，但是又如何得知是因为法师您的祈福才治好的呢？”命莲回
同上。“故事大意：”

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +- - 以下哪个选项不是在迷失竹林发现的？
加一段解析：

> 顺便一提，“黑眼圈的黑白妖兽”是瞎编的。

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +    - source: 《东方求闻史纪》
《东方求闻史纪 / 迷途竹林》

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +    - source: 《东方求闻史纪》
《东方求闻史纪 / 迷途竹林》

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +  - - 迷失竹林
迷途竹林

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +    - source: 《东方求闻史纪》
/ 中有之道

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +    - source: 《东方求闻史纪》
/ 再思之道

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +    - source: 《东方求闻史纪》
**求闻的具体章节以后收录的时候建议自行补全，麻烦了。**

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +    - text: 妖怪之山的内侧流敞着三途河
。

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +    - source: 《东方求闻史纪》
/ 三途河

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +    - source: 《东方求闻史纪》
/ 无名之丘

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +    - text: 在妖怪之山的对面有座很矮的山，在中腹有片绽开着大量铃兰的草原。
在妖怪之山的对面有座很矮的山，在中腹有片绽开着大量铃兰的草原。……因为有着这么黑暗的过去，现在几乎没有人类接近这地方。后来妖怪也不来了，现在此地成了被幻想乡遗忘之地，是为“无名”（×27 很贴切）。

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +    - source: 《东方红魔乡 / Manual / 故事背景》
《东方红魔乡 / 故事背景》

2019-05-06 12:47 UTC, Shigma commented on lib/data/hard.yaml
> +  - a
为啥是 a？不都放在 E 了吗？

2019-05-06 12:47 UTC, Shigma commented on lib/data/normal.yaml
> +- - 以下哪部作品的 Staff 曲名称中不含 Dream（包括片假名）？
> 以下哪部作品的 Staff 曲名称中不含“Dream”（包括片假名）？

2019-05-06 12:47 UTC, Shigma commented on lib/data/normal.yaml
> +    - 空の帰り道 ～ Sky Dream（空中的归路）—— 感情の摩天楼　～ Cosmic Mind（感情的摩天楼）
> 感情の摩天楼　～ Cosmic Mind

改成

> 感情の摩天楼 ～ Cosmic Mind

2019-05-06 12:47 UTC, Shigma commented on lib/data/normal.yaml
> +  - - 素敵な墓場で暮しましょ （在美妙的墓地里住下吧）
多一个空格

2019-05-06 12:47 UTC, Shigma commented on lib/data/normal.yaml
> +    - source: 《东方求闻史纪》
/ 三途河

2019-05-06 13:40 UTC, Shigma commented on lib/data/hard.yaml
> +    - text: 不过这里也隐藏了许多事物。首先是有一间叫永远亭的幽静的大屋。屋子里住着充满了谜团的人类和兔子。其他还有发现会发光的竹子的人，小型雀屋，六十年才会开一次竹花林，竹子底下有着地下妖怪世界等。（顺便一提，“黑眼圈的黑白妖兽”是瞎编的。）
括号内单独成段吧，因为不是引用。

2019-05-06 13:40 UTC, Shigma commented on lib/data/hard.yaml
> +- - 以下哪个选项不是在迷途竹林发现的？
选项 -> 事物

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +    - source: 《东方求闻史纪》
/ 露娜萨·普莉兹姆利巴

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +  - - 雾之湖稍远处
个人感觉这四个选项都应该改成“附近”而不是“稍远处”

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +  - 根据神灵庙结局，神子等人已经从梦殿大祀庙搬到了仙界中。
神子、布都她们觉得，待在妖怪巢穴的寺庙下面不合适，于是在新的地方建造了道场，然后搬过去了。那里被称为仙界，那是一个拥有各种间隙无限宽广的世界。——《东方神灵庙》Ending No. 01

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +  - 求闻史纪中对红魔馆的记载提到图书馆的藏书「听说全是些拾来的魔导书，帕秋莉所著的魔导书和外面世界的书」，求闻史纪中对博丽神社的记载提到「神社附近容易拾到外面世界的东西」，铃奈庵在漫画中有出现外来书籍。雾雨魔法店暂未出现外来书籍。
都改成引用吧~

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +
多一个空行。

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +
多一个空行

2019-05-06 13:40 UTC, Shigma commented on lib/data/lunatic.yaml
> +  - ZUN在东方书谱中曾说过，正方形是是不变，以及自身的表示。
立绘，c

PS：有引文吗……我没找到……

2019-05-06 13:40 UTC, Shigma commented on lib/data/lunatic.yaml
> +  - a
立绘，c

PS：有引文吗……我没找到……

2019-05-06 13:40 UTC, Shigma commented on lib/data/hard.yaml
> +- - 以下那条路是抵达三途河的必经之路？
N 难度

2019-05-06 13:40 UTC, Shigma commented on lib/data/hard.yaml
> +- - 以下那条路最常遇到外面世界的人？
N 难度

2019-05-06 13:40 UTC, Shigma commented on lib/data/hard.yaml
> +- - 三途河位于以下哪个位置？
N 难度

2019-05-06 13:40 UTC, Shigma commented on lib/data/hard.yaml
> +- - 无名之丘位于以下哪个位置？
N 难度

2019-05-06 13:40 UTC, Shigma commented on lib/data/hard.yaml
> +- - 红魔馆位于以下哪个位置？
N 难度

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +    - source: 《东方文花帖 DS / 射命丸文的评价》
《东方文花帖 DS》鬼符「Missing Power」

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +    - source: 《东方深秘录 / 游戏对话 / 丰聪耳神子》
《东方深秘录》丰聪耳神子

（之前的惯例来看，游戏对话是不用写的，因为不是具体的篇章名）

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +  - a
设定，d

同时划分到 Hard 难度

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +    - text: 根据我们的独自调查发现如果一直使用香霖堂的镇纸「智能手机」的话，很容易给颈椎带来深刻的损伤，并会使人患上「手机脖」这种奇病」。
括号不匹配

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +    - source: 《东方文果真报》
章节名补一下。参考同类题目。

2019-05-06 13:40 UTC, Shigma commented on lib/data/normal.yaml
> +    - source: 《东方文果真报》
章节名补一下。参考同类题目。

2019-05-06 13:52 UTC, Kagurazaka-Chiaki commented on lib/data/normal.yaml
> +  - 求闻史纪中对红魔馆的记载提到图书馆的藏书「听说全是些拾来的魔导书，帕秋莉所著的魔导书和外面世界的书」，求闻史纪中对博丽神社的记载提到「神社附近容易拾到外面世界的东西」，铃奈庵在漫画中有出现外来书籍。雾雨魔法店暂未出现外来书籍。
后面两个怎么改呢？

2019-05-06 14:32 UTC, shigma reviewed
好多地方都错了好像……

``` yaml
- type:
  text:
  source:
- xxx
```

2019-05-06 14:32 UTC, Shigma commented on lib/data/hard.yaml
> +    - text: 不过这里也隐藏了许多事物。首先是有一间叫永远亭的幽静的大屋。屋子里住着充满了谜团的人类和兔子。其他还有发现会发光的竹子的人，小型雀屋，六十年才会开一次竹花林，竹子底下有着地下妖怪世界等。
这边格式错了吧。。。

``` yaml
- type:
  text:
  source:
- xxx
```

2019-05-06 14:58 UTC, Kagurazaka-Chiaki commented on lib/data/hard.yaml
> +    - text: 不过这里也隐藏了许多事物。首先是有一间叫永远亭的幽静的大屋。屋子里住着充满了谜团的人类和兔子。其他还有发现会发光的竹子的人，小型雀屋，六十年才会开一次竹花林，竹子底下有着地下妖怪世界等。
吓！我竟然没发现！啊啊啊，对不起……（这次有些偷懒了 ::>_<::

2019-05-06 16:22 UTC, shigma requested changes

2019-05-06 16:22 UTC, Shigma commented on lib/data/easy.yaml
> +  - type: quote
这个原来是对的啊……

2019-05-07 06:04 UTC, Kagurazaka-Chiaki commented
这次应该没问题了……对不起…对不起…感觉这次帮倒忙了◑﹏◐

2019-05-07 12:37 UTC, Shigma commented on lib/data/hard.yaml
> +  - - 祖孙
```
- 后代
- 仇敌
- 弟子
- 祖先
```

2019-05-07 12:37 UTC, Shigma commented on lib/data/normal.yaml
> +  - - type: quote
这里原来是对的

2019-05-07 12:37 UTC, Shigma commented on lib/data/normal.yaml
> +- - 以下那个地方长满了苔藓的尖石？
H 难度

2019-05-07 12:37 UTC, Shigma commented on lib/data/normal.yaml
> +    - 铃奈庵在漫画中有出现外来书籍。雾雨魔法店暂未出现外来书籍。
前半句可以删掉了

2019-05-07 12:37 UTC, Shigma commented on lib/data/hard.yaml
> +- - 零设中，八意永琳和藤原妹红是什么关系？
零设中，八意永琳是藤原妹红的？

2019-05-07 12:37 UTC, Shigma commented on lib/data/hard.yaml
> +- - 零设中，八意永琳和藤原妹红是什么关系？
这批题目暂时全部 Pending，除了一道已经有了的（Echo 竟然出重复……）

这批指xxx与xxx的关系

2019-05-07 12:45 UTC, Kouchya commented on lib/data/hard.yaml
> +  - - 祖孙
好像反了233，妹红是永琳的后代
（不过既然 pending 了那么这里就不是重点了233

2019-05-07 13:01 UTC, shigma approved these changes
我觉得没什么问题了。

@Kouchya 你也看看吧

2019-05-07 15:24 UTC, Kouchya requested changes
辛苦了，还有一些小细节麻烦改一下~

2019-05-07 15:24 UTC, Kouchya commented on lib/data/hard.yaml
> +- - 零设中，拉尔瓦的真实身份为以下哪个？
角色名写全？

2019-05-07 15:24 UTC, Kouchya commented on lib/data/lunatic.yaml
> +      source: 《东方文花帖DS / 胎儿之梦》
DS 前面加个空格叭

2019-05-07 15:24 UTC, Kouchya commented on lib/data/normal.yaml
> +- - ZUN 经常在游戏曲中加入一段经典旋律（do fa so si so fa），以下哪首音乐中没有出现这段旋律？
第四个音是降 si，@Shigma 看看是写汉字还是用降音符号？（我不清楚唱名的文本表示

2019-05-07 15:24 UTC, Kouchya commented on lib/data/normal.yaml
> +- - 以下那条路是抵达三途河的必经之路？
那→哪

2019-05-07 15:24 UTC, Kouchya commented on lib/data/normal.yaml
> +- - 以下那条路最常遇到外面世界的人？
那→哪

2019-05-07 15:24 UTC, Kouchya commented on lib/data/normal.yaml
> +    text: 妖怪之山的内侧流敞着三途河。
敞→淌

2019-05-07 15:24 UTC, Kouchya commented on lib/data/normal.yaml
> +      text: 图书馆内除了魔导书还有其它书籍，除了魔导书以外的大部分是外面世界的书（×2幻想乡的书多数是手写的，印刷制成的很少。）。
×2 后面加个空格叭

2019-05-08 15:57 UTC, Kouchya requested changes
抱歉，还有最后一个错别字更正，辛苦你啦
（感觉要被打死了）

2019-05-08 15:57 UTC, Kouchya commented on lib/data/hard.yaml
> +- - 以下那个地方长满了苔藓的尖石？
那→哪

2019-05-08 16:21 UTC, Kouchya approved these changes

2019-05-08 16:21 UTC, merged