加了几道题？
uzkk/quiz pull request #36
Opened 2019-05-08 18:38 UTC by Kagurazaka-Chiaki

加了八道题，其中有两题放在了Pending，因为感觉有些疑虑……（

2019-05-08 18:38 UTC, Kagurazaka-Chiaki commented
欸？为什么上一个分支会有冲突啊……？

2019-05-08 20:06 UTC, Kouchya requested changes
辛苦了，有些需要改动的地方，其中一些可能还要跟孤梦进一步商量~

2019-05-08 20:06 UTC, Kouchya commented on lib/data/hard.yaml
> +- - 《东方求闻史纪》的背面没有出现以下哪位角色？
背面或许改封底听上去更正式些？@Shigma 你看要改吗

2019-05-08 20:06 UTC, Kouchya commented on lib/data/hard.yaml
> +      text: 栖息于玄武之沢的河童中的一员。河童的数量众多，好像都构筑起了一个社会体系。
沢→泽，前者是日语用字，在这里还是翻译成规范汉字叭

2019-05-08 20:06 UTC, Kouchya commented on lib/data/hard.yaml
> +      source: 《东方茨歌仙 / 第43话 / 博丽神社富不起来》
现在对作品章节的引用还没有规范，@Shigma 考虑一下是《作品名 / 第 [阿拉伯数字] 话 / 标题》，还是《作品名 / 第 [汉字数字] 话 / 标题》，还是上述两种中的一种去掉第三项标题，还是别的方式（比如第 xx 话放书名号外）？

2019-05-08 20:06 UTC, Kouchya commented on lib/data/normal.yaml
> +    - 遥か３８万キロのボヤージュ（遥遥38万公里的航程）
括号里中文名的 38 前后加个空格叭~

2019-05-08 20:06 UTC, Kouchya commented on lib/data/hard.yaml
> +      text: 屋台は河童や妖精達への外注だからねぇ
摊位都被河童和妖精们承包了。

2019-05-08 20:06 UTC, Kouchya commented on lib/data/pending.yaml
> +- - 传说中，雾之湖能钓到的大型鱼最长是多长？
这题可能有争议？@Shigma

2019-05-08 20:06 UTC, Kouchya commented on lib/data/pending.yaml
> +    - 玄武泽
玄武之泽

2019-05-08 20:15 UTC, Kagurazaka-Chiaki commented
不睡觉的嘛？Σ(っ °Д °;)っ

2019-05-09 02:13 UTC, Shigma commented on lib/data/normal.yaml
> +    - 遥か３８万キロのボヤージュ（遥遥 38 万公里的航程）
换成半角38，加空格

2019-05-09 02:13 UTC, Shigma commented on lib/data/normal.yaml
> +- - 博丽灵梦初遇少名针妙丸是在辉针城的哪一处？
我觉得或许可以E

@kouchya

2019-05-09 11:52 UTC, Shigma commented on lib/data/hard.yaml
> +  - 买一本看看就知道了~
建议这个解析写出出现的全部角色。

2019-05-09 11:52 UTC, Shigma commented on lib/data/hard.yaml
> +    - 各种官方漫画中，河童们经常在博丽神社摆摊，魔法之森目前未记载有河童出没。
前半句话已经提到了，所以没有必要再写一遍了。

2019-05-09 11:52 UTC, Shigma commented on lib/data/pending.yaml
> +# 冻鱼是钓上来之后被琪露诺冻住的嘛？
这题的问题在哪？

2019-05-09 11:52 UTC, Shigma commented on lib/data/pending.yaml
> +- - 传说中，雾之湖能钓到的大型鱼最长是多长？
十寻
二寻
五寻
十二寻

选项改成这些。然后下面的换算关系去掉

2019-05-09 22:10 UTC, Kagurazaka-Chiaki commented on lib/data/normal.yaml
> +- - 博丽灵梦初遇少名针妙丸是在辉针城的哪一处？
按解析来看……至少要过六面才行吧？

2019-05-09 22:11 UTC, Kagurazaka-Chiaki commented on lib/data/pending.yaml
> +# 冻鱼是钓上来之后被琪露诺冻住的嘛？
一直以为……冻鱼不是物种来着……（

2019-05-10 08:41 UTC, Shigma commented on lib/data/hard.yaml
> +    text: 但是，似乎每年发病的症状都不一样，似乎不能用寻常的方法去判断（×1 这是以每年见到第一个发病人的地点来命名的，例如说玄武池B型啊荞麦屋A型之类来改疾病名称）。
B 空格。

2019-05-10 08:41 UTC, Shigma commented on lib/data/hard.yaml
> +  - 东方地灵殿中，灵梦选择不同的志愿角色时，对应的子机颜色也有所不同。八云紫为紫色，伊吹萃香为蓝色，射命丸文为红色。
支援，抱歉我打错了

2019-05-10 08:41 UTC, Shigma commented on lib/data/normal.yaml
> +    - type: quote
缩进错了哦

2019-05-10 09:23 UTC, merged